# Generated by Django 3.1.14 on 2022-07-14 13:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon_entities', '0003_auto_20220712_1254'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pokemon',
            old_name='evolution',
            new_name='pokemon',
        ),
        migrations.AlterField(
            model_name='pokemonentity',
            name='pokemon',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pokemons', to='pokemon_entities.pokemon', verbose_name='Вид покемона'),
        ),
    ]
