# Generated by Django 3.1.14 on 2022-07-14 14:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon_entities', '0004_auto_20220714_1658'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pokemon',
            name='pokemon',
        ),
        migrations.AddField(
            model_name='pokemon',
            name='next_evolution',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='previous_evolution', to='pokemon_entities.pokemon', verbose_name='Эволюция покемона'),
        ),
    ]
